---
- name: Include install task
  include_tasks: install.yml
  when: ('install' in ansible_run_tags) or (ansible_run_tags|length == 0)

- name: Remove Apollo server container
  docker_container:
    name: apollo-server
    state: absent

- name: Remove apollo-server container image
  docker_image:
    name: apollo-server
    state: absent

- name: Include standup task
  include_tasks: standup.yml
  when: ('standup' in ansible_run_tags) or (ansible_run_tags|length == 0)
