---
- hosts: all
  become: True

  vars:
    pip_install_packages:
      - name: docker

  roles:
    - docker
    - geerlingguy.pip
    - geerlingguy.docker

- hosts: upstream
  become: True
  vars_files:
    - ./vars/tests.yml
    - ./vars/upstream.yml

  roles:
    - role: upstream
      standup: True

- hosts: load-generator
  become: True
  vars_files:
    - ./vars/tests.yml
    - ./vars/upstream.yml

  roles:
    - role: load-generator
      is_upstream: True
      host_ip: "{{ hostvars.upstream.ansible_facts.default_ipv4.address }}"
      host_port: "{{ upstream.service.port }}"
      results_filename: bench-upstream.txt

- hosts: tyk
  become: True
  vars_files:
    - ./vars/tests.yml
    - ./vars/gateway.yml
    - ./vars/upstream.yml

  roles:
    - role: tyk
      upstream_host: "{{ hostvars.upstream.ansible_facts.default_ipv4.address }}"
      standup: True

- hosts: load-generator
  become: True
  vars_files:
    - ./vars/tests.yml
    - ./vars/gateway.yml

  roles:
    - role: load-generator
      is_upstream: False
      host_ip: "{{ hostvars.tyk.ansible_facts.default_ipv4.address }}"
      host_port: "{{ gateway.service.port }}"
      results_filename: bench-tyk.txt

- hosts: upstream
  become: True

  roles:
    - role: upstream
      cleanup: True

- hosts: tyk
  become: True

  roles:
    - role: tyk
      cleanup: True
