---
# Install docker on all servers.
- hosts: all
  become: True
  vars:
    pip_install_packages:
      - name: docker
  roles:
    - geerlingguy.pip
    - geerlingguy.docker
  tags:
    - install

# Install htop on all servers (Optional)
- hosts: all
  become: True
  roles:
    - htop
  tags:
    - htop

# Allows gathering of ansible_facts to discover the internal IPs of the
# servers when running the test tag.
- hosts: all
  tasks:
  - name: Collect ansible_facts to discover internal IPs
    debug:
      msg: Discovering internal IP...
  tags:
    - test

# Stand up upstream services.
- hosts: upstream
  become: True
  vars_files:
    - ./vars/tests.yml
    - ./vars/services.yml
  roles:
    - upstream
  tags:
    - standup

# Benchmark upstream service
- hosts: load-generator
  become: True
  vars_files:
    - ./vars/tests.yml
    - ./vars/services.yml
  tasks:
    - name: Include load-generator role
      vars:
        label: upstream
      include_role:
        name: load-generator
      when: query_type == 'REST'
  tags:
    - test

# Stand up Tyk gateway
- hosts: tyk
  become: True
  vars_files:
    - ./vars/tests.yml
    - ./vars/services.yml
  roles:
    - role: tyk
  tags:
    - install
    - standup

# Benchmark Tyk gateway
- hosts: load-generator
  become: True
  vars_files:
    - ./vars/tests.yml
    - ./vars/services.yml
  roles:
    - role: load-generator
      label: tyk
  tags:
    - test

# Stand up Kong gateway
- hosts: kong
  become: True
  vars_files:
    - ./vars/tests.yml
    - ./vars/services.yml
  tasks:
    - name: Include kong role
      include_role:
        name: kong
      when: (query_type == 'REST') and ('kong' in test_services)
  tags:
    - standup

# Benchmark Kong gateway
- hosts: load-generator
  become: True
  vars_files:
    - ./vars/tests.yml
    - ./vars/services.yml
  tasks:
    - name: Include load-generator role
      vars:
        label: kong
      include_role:
        name: load-generator
      when: (query_type == 'REST') and ('kong' in test_services)
  tags:
    - test

# Stand up Apollo server
- hosts: apollo
  become: True
  vars_files:
    - ./vars/tests.yml
    - ./vars/services.yml
  tasks:
    - name: Include apollo-server role
      include_role:
        name: apollo-server
      when: (query_type != 'REST') and ('apollo' in test_services)
  tags:
    - install
    - standup

# Benchmark Apollo server
- hosts: load-generator
  become: True
  vars_files:
    - ./vars/tests.yml
    - ./vars/services.yml
  tasks:
    - name: Include load-generator role
      vars:
        label: apollo
      include_role:
        name: load-generator
      when: (query_type != 'REST') and ('apollo' in test_services)
  tags:
    - test

# Clean up upstream services
- hosts: upstream
  become: True
  vars_files:
    - ./vars/tests.yml
  roles:
    - upstream
  tags:
    - cleanup

# Clean up Tyk gateway services
- hosts: tyk
  become: True
  roles:
    - tyk
  tags:
    - cleanup

# Clean up Kong gateway services
- hosts: kong
  become: True
  vars_files:
    - ./vars/tests.yml
  tasks:
    - name: Include kong role
      include_role:
        name: kong
      when: (query_type == 'REST') and ('kong' in test_services)
  tags:
    - cleanup

# Clean up Apollo services
- hosts: apollo
  become: True
  vars_files:
    - ./vars/tests.yml
  tasks:
    - name: Include apollo-server role
      include_role:
        name: apollo-server
      when: (query_type != 'REST') and ('apollo' in test_services)
  tags:
    - cleanup
