sudo ansible-playbook aws.playbook.yml -t standup -e '{ "aws_instance_type": "t3.medium" }'
sudo ansible-playbook playbook.yml -i hosts/t3.medium-aws-hosts.yml -t install -t standup -e '{ "query_type": "REST" }'
sudo ansible-playbook playbook.yml -i hosts/t3.medium-aws-hosts.yml -t test -e '{ "query_type": "REST", "test_services": [ "kong" ], "prefix": "t3.medium-aws-1" }'
sudo ansible-playbook playbook.yml -i hosts/t3.medium-aws-hosts.yml -t test -e '{ "query_type": "REST", "test_services": [ "kong" ], "prefix": "t3.medium-aws-2" }'
sudo ansible-playbook playbook.yml -i hosts/t3.medium-aws-hosts.yml -t test -e '{ "query_type": "REST", "test_services": [ "kong" ], "prefix": "t3.medium-aws-3" }'
sudo ansible-playbook aws.playbook.yml -t cleanup -e '{ "aws_instance_type": "t3.medium" }'

sudo ansible-playbook aws.playbook.yml -t standup -e '{ "aws_instance_type": "m5.large" }'
sudo ansible-playbook playbook.yml -i hosts/m5.large-aws-hosts.yml -t install -t standup -e '{ "query_type": "REST" }'
sudo ansible-playbook playbook.yml -i hosts/m5.large-aws-hosts.yml -t test -e '{ "query_type": "REST", "test_services": [ "kong" ], "prefix": "m5.large-aws-1" }'
sudo ansible-playbook playbook.yml -i hosts/m5.large-aws-hosts.yml -t test -e '{ "query_type": "REST", "test_services": [ "kong" ], "prefix": "m5.large-aws-2" }'
sudo ansible-playbook playbook.yml -i hosts/m5.large-aws-hosts.yml -t test -e '{ "query_type": "REST", "test_services": [ "kong" ], "prefix": "m5.large-aws-3" }'
sudo ansible-playbook aws.playbook.yml -t cleanup -e '{ "aws_instance_type": "m5.large" }'

sudo ansible-playbook aws.playbook.yml -t standup -e '{ "aws_instance_type": "c5.xlarge" }'
sudo ansible-playbook playbook.yml -i hosts/c5.xlarge-aws-hosts.yml -t install -t standup -e '{ "query_type": "REST" }'
sudo ansible-playbook playbook.yml -i hosts/c5.xlarge-aws-hosts.yml -t test -e '{ "query_type": "REST", "test_services": [ "kong" ], "prefix": "c5.xlarge-aws-1" }'
sudo ansible-playbook playbook.yml -i hosts/c5.xlarge-aws-hosts.yml -t test -e '{ "query_type": "REST", "test_services": [ "kong" ], "prefix": "c5.xlarge-aws-2" }'
sudo ansible-playbook playbook.yml -i hosts/c5.xlarge-aws-hosts.yml -t test -e '{ "query_type": "REST", "test_services": [ "kong" ], "prefix": "c5.xlarge-aws-3" }'
sudo ansible-playbook aws.playbook.yml -t cleanup -e '{ "aws_instance_type": "c5.xlarge" }'

sudo ansible-playbook gcp.playbook.yml -t standup -e '{ "gcp_machine_type": "n1-standard-1" }'
sudo ansible-playbook playbook.yml -i hosts/n1-standard-1-gcp-hosts.yml -t install -t standup -e '{ "query_type": "REST" }'
sudo ansible-playbook playbook.yml -i hosts/n1-standard-1-gcp-hosts.yml -t test -e '{ "query_type": "REST", "test_services": [ "kong" ], "prefix": "n1-standard-1-gcp-1" }'
sudo ansible-playbook playbook.yml -i hosts/n1-standard-1-gcp-hosts.yml -t test -e '{ "query_type": "REST", "test_services": [ "kong" ], "prefix": "n1-standard-1-gcp-2" }'
sudo ansible-playbook playbook.yml -i hosts/n1-standard-1-gcp-hosts.yml -t test -e '{ "query_type": "REST", "test_services": [ "kong" ], "prefix": "n1-standard-1-gcp-3" }'
sudo ansible-playbook gcp.playbook.yml -t cleanup -e '{ "gcp_machine_type": "n1-standard-1" }'

sudo ansible-playbook gcp.playbook.yml -t standup -e '{ "gcp_machine_type": "n1-standard-4" }'
sudo ansible-playbook playbook.yml -i hosts/n1-standard-4-gcp-hosts.yml -t install -t standup -e '{ "query_type": "REST" }'
sudo ansible-playbook playbook.yml -i hosts/n1-standard-4-gcp-hosts.yml -t test -e '{ "query_type": "REST", "test_services": [ "kong" ], "prefix": "n1-standard-4-gcp-1" }'
sudo ansible-playbook playbook.yml -i hosts/n1-standard-4-gcp-hosts.yml -t test -e '{ "query_type": "REST", "test_services": [ "kong" ], "prefix": "n1-standard-4-gcp-2" }'
sudo ansible-playbook playbook.yml -i hosts/n1-standard-4-gcp-hosts.yml -t test -e '{ "query_type": "REST", "test_services": [ "kong" ], "prefix": "n1-standard-4-gcp-3" }'
sudo ansible-playbook gcp.playbook.yml -t cleanup -e '{ "gcp_machine_type": "n1-standard-4" }'

sudo ansible-playbook gcp.playbook.yml -t standup -e '{ "gcp_machine_type": "n1-highcpu-16" }'
sudo ansible-playbook playbook.yml -i hosts/n1-highcpu-16-gcp-hosts.yml -t install -t standup -e '{ "query_type": "REST" }'
sudo ansible-playbook playbook.yml -i hosts/n1-highcpu-16-gcp-hosts.yml -t test -e '{ "query_type": "REST", "test_services": [ "kong" ], "prefix": "n1-highcpu-16-gcp-1" }'
sudo ansible-playbook playbook.yml -i hosts/n1-highcpu-16-gcp-hosts.yml -t test -e '{ "query_type": "REST", "test_services": [ "kong" ], "prefix": "n1-highcpu-16-gcp-2" }'
sudo ansible-playbook playbook.yml -i hosts/n1-highcpu-16-gcp-hosts.yml -t test -e '{ "query_type": "REST", "test_services": [ "kong" ], "prefix": "n1-highcpu-16-gcp-3" }'
sudo ansible-playbook gcp.playbook.yml -t cleanup -e '{ "gcp_machine_type": "n1-highcpu-16" }'
