---
- name: Include install task
  include_tasks: install.yml
  when: (('install' in ansible_run_tags) or (ansible_run_tags|length == 0)) and not ('saas' in ansible_run_tags)

- name: Remove Tyk Gateway container
  docker_container:
    name: tyk-gateway
    state: absent
  when: not ('saas' in ansible_run_tags)

- name: Include standup task
  include_tasks: standup.yml
  when: ('standup' in ansible_run_tags) or (ansible_run_tags|length == 0)
