---
- name: Create users-subgraph.json
  template:
    src: tyk/users-subgraph.j2
    dest: "{% if 'saas' in ansible_run_tags %}./saas/apps/users-subgraph.json{% else %}/opt/tyk-gateway/apps/users-subgraph.json{% endif %}"

- name: Create posts-subgraph.json
  template:
    src: tyk/posts-subgraph.j2
    dest: "{% if 'saas' in ansible_run_tags %}./saas/apps/posts-subgraph.json{% else %}/opt/tyk-gateway/apps/posts-subgraph.json{% endif %}"

- name: Create comments-subgraph.json
  template:
    src: tyk/comments-subgraph.j2
    dest: "{% if 'saas' in ansible_run_tags %}./saas/apps/comments-subgraph.json{% else %}/opt/tyk-gateway/apps/comments-subgraph.json{% endif %}"
