---
- name: Include terminate_instance task to terminate Upstream vm
  include_tasks: terminate_instance.yml
  vars:
    title: Upstream
    type: upstream

- name: Include terminate_instance task to terminate Load Generator vm
  include_tasks: terminate_instance.yml
  vars:
    title: Load Generator
    type: load

- name: Include terminate_instance task to terminate Tyk Dependencies vm
  include_tasks: terminate_instance.yml
  vars:
    title: Tyk Dependencies
    type: tyk-dependencies
  when: ('tyk' in test_services)

- name: Include terminate_instance task to terminate Tyk vm
  include_tasks: terminate_instance.yml
  vars:
    title: Tyk
    type: tyk
  when: ('tyk' in test_services)

- name: Include terminate_instance task to terminate Kong Dependencies vm
  include_tasks: terminate_instance.yml
  vars:
    title: Kong Dependencies
    type: kong-dependencies
  when: ('kong' in test_services)

- name: Include terminate_instance task to terminate Kong vm
  include_tasks: terminate_instance.yml
  vars:
    title: Kong
    type: kong
  when: ('kong' in test_services)

- name: Include terminate_instance task to terminate Apollo vm
  include_tasks: terminate_instance.yml
  vars:
    title: Apollo
    type: apollo
  when: ('apollo' in test_services)

- name: Terminate GCP firewall instance
  gcp_compute_firewall:
    state: absent
    name: "{{ gcp_machine_type }}-firewall"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_auth_kind }}"
    service_account_file: "{{ gcp_service_account_file }}"

- name: Terminate GCP network instance
  gcp_compute_network:
    state: absent
    name: "{{ gcp_machine_type }}-network"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_auth_kind }}"
    service_account_file: "{{ gcp_service_account_file }}"
