---
- name: Terminate {{ title }} GCP compute instance
  gcp_compute_instance:
    state: absent
    name: "{{ gcp_machine_type }}-{{ type }}"
    project: "{{ gcp_project }}"
    zone: "{{ gcp_zone }}"
    auth_kind: "{{ gcp_auth_kind }}"
    service_account_file: "{{ gcp_service_account_file }}"

- name: Terminate {{ title }} GCP address instance
  gcp_compute_address:
    state: absent
    name: "{{ gcp_machine_type }}-{{ type }}-address"
    project: "{{ gcp_project }}"
    region: "{{ gcp_region }}"
    auth_kind: "{{ gcp_auth_kind }}"
    service_account_file: "{{ gcp_service_account_file }}"
