---
- name: Create API key
  uri:
    url: http://{{ host_ip }}:{{ host_port }}/tyk/keys/create
    method: POST
    body_format: json
    headers:
      Content-Type: "application/json"
      x-tyk-authorization: "{{ gateway.secret }}"
    body: "{ \"access_rights\": { \"1\": { \"allowed_urls\": [], \"api_id\": \"1\", \"api_name\": \"Tyk Test API\", \"limit\": null, \"versions\": [ \"Default\" ] } }, \"allowance\": 100000, \"expires\": 0, \"org_id\": \"default\", \"per\": 1, \"quota_max\": -1, \"quota_remaining\": -1, \"quota_renewal_rate\": -1, \"quota_renews\": 1568655187, \"rate\": 100000, \"throttle_interval\": -1, \"throttle_retry_limit\": -1 }"
  register: response
  when: is_upstream == false and enable_auth == true

- name: Launch Load Generator
  docker_container:
    name: load-generator
    state: started
    image: rcmorano/docker-hey
    detach: no
    command: "{% if is_upstream %}-z 10s -q 1500 http://{{ host_ip }}:{{ host_port }}/json/valid{% elif enable_auth %}-z 10s -q 1500 -H \"Authorization: {{ response.json.key }}\" http://{{ host_ip }}:{{ host_port }}/api/json/valid{% else %}-z 10s -q 1500 http://{{ host_ip }}:{{ host_port }}/api/json/valid{% endif %}"
  register: output

- name: Copy result to local
  local_action: copy content={{ output.container.Output }} dest=./{{ results_filename }}

- name: Remove Load Generator container
  docker_container:
    name: load-generator
    state: absent
