---
- name: Include federation-standup task
  include_tasks: federation-standup.yml
  when: ('standup' in ansible_run_tags)

- name: Include federation-cleanup task
  include_tasks: federation-cleanup.yml
  when: ('cleanup' in ansible_run_tags)
