---
- name: Launch users container
  docker_container:
    name: users
    state: started
    image: zalbiraw/go-api-test-service
    ports:
      - "{{ services.upstream.subgraphs.users.port }}:{{ services.upstream.subgraphs.users.port }}"
    env:
      GOGC: "3200"
      PORT: "{{ services.upstream.subgraphs.users.port }}"
    ulimits: "nofile:80000:80000"
    entrypoint: ./users/server

- name: Launch posts container
  docker_container:
    name: posts
    state: started
    image: zalbiraw/go-api-test-service
    ports:
      - "{{ services.upstream.subgraphs.posts.port }}:{{ services.upstream.subgraphs.posts.port }}"
    env:
      GOGC: "3200"
      PORT: "{{ services.upstream.subgraphs.posts.port }}"
    ulimits: "nofile:80000:80000"
    entrypoint: ./posts/server

- name: Launch comments container
  docker_container:
    name: comments
    state: started
    image: zalbiraw/go-api-test-service
    ports:
      - "{{ services.upstream.subgraphs.comments.port }}:{{ services.upstream.subgraphs.comments.port }}"
    env:
      GOGC: "3200"
      PORT: "{{ services.upstream.subgraphs.comments.port }}"
    ulimits: "nofile:80000:80000"
    entrypoint: ./comments/server
