---
- name: Launch upstream container
  docker_container:
    name: upstream
    state: started
    image: "{% if query_type == 'REST' %}mangomm/go-bench-suite{% elif query_type == 'UDG' %}svenwal/jsonplaceholder{% endif %}"
    ports:
      - "{{ upstream.service.port }}:{% if query_type == 'REST' %}8000{% elif query_type == 'UDG' %}3000{% endif %}"
    ulimits: "nofile:80000:80000"
    command: "{% if query_type == 'REST' %}./go-bench-suite upstream{% endif %}"
  when: standup is defined and standup

- name: Remove upstream container
  docker_container:
    name: upstream
    state: absent
  when: cleanup is defined and cleanup
