---
- name: Launch upstream container
  docker_container:
    name: upstream
    state: started
    image: "{% if query_type == 'REST' %}mangomm/go-bench-suite{% elif query_type == 'STITCH' %}mangomm/jsonplaceholder{% endif %}"
    ports:
      - "{{ upstream.service.port }}:8000"
    env:
      GOGC: "3200"
    ulimits: "nofile:80000:80000"
    command: "{% if query_type == 'REST' %}./go-bench-suite upstream{% endif %}"
  when: standup is defined and standup and query_type != 'FEDERATE'

- name: Remove upstream container
  docker_container:
    name: upstream
    state: absent
  when: cleanup is defined and cleanup and query_type != 'FEDERATE'

- name: Launch users container
  docker_container:
    name: users
    state: started
    image: zalbiraw/go-api-test-service
    ports:
      - "{{ upstream.services.users.port }}:4001"
    env:
      GOGC: "3200"
      PORT: "4001"
    ulimits: "nofile:80000:80000"
    entrypoint: ./users/server
  when: standup is defined and standup and query_type == 'FEDERATE'

- name: Launch posts container
  docker_container:
    name: posts
    state: started
    image: zalbiraw/go-api-test-service
    ports:
      - "{{ upstream.services.posts.port }}:4002"
    env:
      GOGC: "3200"
      PORT: "4002"
    ulimits: "nofile:80000:80000"
    entrypoint: ./posts/server
  when: standup is defined and standup and query_type == 'FEDERATE'

- name: Launch comments container
  docker_container:
    name: comments
    state: started
    image: zalbiraw/go-api-test-service
    ports:
      - "{{ upstream.services.comments.port }}:4003"
    env:
      GOGC: "3200"
      PORT: "4003"
    ulimits: "nofile:80000:80000"
    entrypoint: ./comments/server
  when: standup is defined and standup and query_type == 'FEDERATE'

- name: Remove users container
  docker_container:
    name: users
    state: absent
  when: cleanup is defined and cleanup and query_type == 'FEDERATE'

- name: Remove posts container
  docker_container:
    name: posts
    state: absent
  when: cleanup is defined and cleanup and query_type == 'FEDERATE'

- name: Remove comments container
  docker_container:
    name: comments
    state: absent
  when: cleanup is defined and cleanup and query_type == 'FEDERATE'
