---
- name: Launch upstream container
  docker_container:
    name: upstream
    state: started
    image: "{% if query_type == 'REST' %}mangomm/go-bench-suite{% elif query_type == 'STITCH' %}mangomm/jsonplaceholder{% endif %}"
    ports:
      - "{{ services.upstream.service.port }}:8000"
    env:
      GOGC: "3200"
    ulimits: "nofile:80000:80000"
    command: "{% if query_type == 'REST' %}./go-bench-suite upstream{% endif %}"
  when: ('standup' in ansible_run_tags) or (ansible_run_tags|length == 0)

- name: Remove upstream container
  docker_container:
    name: upstream
    state: absent
  when: ('cleanup' in ansible_run_tags) or (ansible_run_tags|length == 0)
