---
- name: Terminate Upstream EC2 instance
  ec2_instance:
    state: absent
    name: "{{ aws_instance_type }}-upstream"
    region: "{{ aws_region }}"
    instance_type: "{{ aws_instance_type }}"
    vpc_subnet_id: "{{ aws_vpc_subnet_id }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"

- name: Terminate Load Generator EC2 instance
  ec2_instance:
    state: absent
    name: "{{ aws_instance_type }}-load"
    region: "{{ aws_region }}"
    instance_type: "{{ aws_instance_type }}"
    vpc_subnet_id: "{{ aws_vpc_subnet_id }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"

- name: Terminate Tyk EC2 instance
  ec2_instance:
    state: absent
    name: "{{ aws_instance_type }}-tyk"
    region: "{{ aws_region }}"
    instance_type: "{{ aws_instance_type }}"
    vpc_subnet_id: "{{ aws_vpc_subnet_id }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  when: ('tyk' in test_services)

- name: Terminate Kong EC2 instance
  ec2_instance:
    state: absent
    name: "{{ aws_instance_type }}-kong"
    region: "{{ aws_region }}"
    instance_type: "{{ aws_instance_type }}"
    vpc_subnet_id: "{{ aws_vpc_subnet_id }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  when: ('kong' in test_services)

- name: Terminate Apollo EC2 instance
  ec2_instance:
    state: absent
    name: "{{ aws_instance_type }}-apollo"
    region: "{{ aws_region }}"
    instance_type: "{{ aws_instance_type }}"
    vpc_subnet_id: "{{ aws_vpc_subnet_id }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  when: ('apollo' in test_services)
