---
- name: Provision Upstream EC2 instance
  ec2_instance:
    name: "{{ aws_instance_type }}-upstream"
    instance_type: "{{ aws_instance_type }}"
    region: "{{ aws_region }}"
    image_id: "{{ aws_image }}"
    vpc_subnet_id: "{{ aws_vpc_subnet_id }}"
    security_group: "{{ aws_group }}"
    key_name: "{{ aws_key_name }}"
    network:
      assign_public_ip: yes
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  register: upstream
  until: upstream.instances[0].public_dns_name != ""
  retries: 10
  delay: 5

- name: Provision Load Generator EC2 instance
  ec2_instance:
    name: "{{ aws_instance_type }}-load"
    instance_type: "{{ aws_instance_type }}"
    region: "{{ aws_region }}"
    image_id: "{{ aws_image }}"
    vpc_subnet_id: "{{ aws_vpc_subnet_id }}"
    security_group: "{{ aws_group }}"
    key_name: "{{ aws_key_name }}"
    network:
      assign_public_ip: yes
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  register: load
  until: load.instances[0].public_dns_name != ""
  retries: 10
  delay: 5

- name: Provision Tyk Dependencies EC2 instance
  ec2_instance:
    name: "{{ aws_instance_type }}-tyk-dependencies"
    instance_type: "{{ aws_instance_type }}"
    region: "{{ aws_region }}"
    image_id: "{{ aws_image }}"
    vpc_subnet_id: "{{ aws_vpc_subnet_id }}"
    security_group: "{{ aws_group }}"
    key_name: "{{ aws_key_name }}"
    network:
      assign_public_ip: yes
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  register: tyk_dependencies
  until: tyk_dependencies.instances[0].public_dns_name != ""
  retries: 10
  delay: 5
  when: ('tyk' in test_services)

- name: Provision Tyk EC2 instance
  ec2_instance:
    name: "{{ aws_instance_type }}-tyk"
    instance_type: "{{ aws_instance_type }}"
    region: "{{ aws_region }}"
    image_id: "{{ aws_image }}"
    vpc_subnet_id: "{{ aws_vpc_subnet_id }}"
    security_group: "{{ aws_group }}"
    key_name: "{{ aws_key_name }}"
    network:
      assign_public_ip: yes
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  register: tyk
  until: tyk.instances[0].public_dns_name != ""
  retries: 10
  delay: 5
  when: ('tyk' in test_services)

- name: Provision Kong Dependencies EC2 instance
  ec2_instance:
    name: "{{ aws_instance_type }}-kong-dependencies"
    instance_type: "{{ aws_instance_type }}"
    region: "{{ aws_region }}"
    image_id: "{{ aws_image }}"
    vpc_subnet_id: "{{ aws_vpc_subnet_id }}"
    security_group: "{{ aws_group }}"
    key_name: "{{ aws_key_name }}"
    network:
      assign_public_ip: yes
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  register: kong_dependencies
  until: kong_dependencies.instances[0].public_dns_name != ""
  retries: 10
  delay: 5
  when: ('kong' in test_services)

- name: Provision Kong EC2 instance
  ec2_instance:
    name: "{{ aws_instance_type }}-kong"
    instance_type: "{{ aws_instance_type }}"
    region: "{{ aws_region }}"
    image_id: "{{ aws_image }}"
    vpc_subnet_id: "{{ aws_vpc_subnet_id }}"
    security_group: "{{ aws_group }}"
    key_name: "{{ aws_key_name }}"
    network:
      assign_public_ip: yes
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  register: kong
  until: kong.instances[0].public_dns_name != ""
  retries: 10
  delay: 5
  when: ('kong' in test_services)

- name: Provision Apollo EC2 instance
  ec2_instance:
    name: "{{ aws_instance_type }}-apollo"
    instance_type: "{{ aws_instance_type }}"
    region: "{{ aws_region }}"
    image_id: "{{ aws_image }}"
    vpc_subnet_id: "{{ aws_vpc_subnet_id }}"
    security_group: "{{ aws_group }}"
    key_name: "{{ aws_key_name }}"
    network:
      assign_public_ip: yes
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  register: apollo
  until: apollo.instances[0].public_dns_name != ""
  retries: 10
  delay: 5
  when: ('apollo' in test_services)

- name: Create {{ aws_instance_type }}-aws-hosts.yml
  vars:
    hosts:
      upstream: "{{ upstream.instances[0].public_dns_name }}"
      load: "{{ load.instances[0].public_dns_name }}"
      tyk: "{% if 'tyk' in test_services %}{{ tyk.instances[0].public_dns_name }}{% endif %}"
      tyk_dependencies: "{% if 'tyk' in test_services %}{{ tyk_dependencies.instances[0].public_dns_name }}{% endif %}"
      kong: "{% if 'kong' in test_services %}{{ kong.instances[0].public_dns_name }}{% endif %}"
      kong_dependencies: "{% if 'kong' in test_services %}{{ kong_dependencies.instances[0].public_dns_name }}{% endif %}"
      apollo: "{% if 'apollo' in test_services %}{{ apollo.instances[0].public_dns_name }}{% endif %}"
  template:
    src: hosts.j2
    dest: ./hosts/{{ aws_instance_type }}-aws-hosts.yml
