---
- name: Install docker using the geerlingguy.docker role
  include_role:
    name: geerlingguy.docker
  when: ansible_distribution != "Amazon" and ansible_distribution_major_version != "2"

- name: Disable docker-ce-stable repo
  shell: yum-config-manager --disable docker-ce-stable
  when: ansible_distribution == "Amazon" and ansible_distribution_major_version == "2"

- name: Update all packages
  yum:
    name: '*'
    state: latest
  when: ansible_distribution == "Amazon" and ansible_distribution_major_version == "2"

- name: Install docker
  shell: amazon-linux-extras install docker -y
  when: ansible_distribution == "Amazon" and ansible_distribution_major_version == "2"

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: started
    enabled: true
  when: ansible_distribution == "Amazon" and ansible_distribution_major_version == "2"

- name: Install pip using the geerlingguy.pip role
  include_role:
    name: geerlingguy.pip
  vars:
    pip_install_packages:
      name: docker
  when: ansible_distribution != "Amazon" and ansible_distribution_major_version != "2"

- name: Ensure Pip is installed.
  package:
    name: python2-pip
    state: present
  when: ansible_distribution == "Amazon" and ansible_distribution_major_version == "2"

- name: Ensure docker python packages are installed.
  pip:
    name: docker
  when: ansible_distribution == "Amazon" and ansible_distribution_major_version == "2"
