---
- name: Update system packages
  package:
    name: "*"
    state: latest
    update_cache: yes

- name: Include redhat task
  include_tasks: redhat.yml
  when: ansible_distribution == "RedHat" or ansible_distribution == "CentOS"

- name: Install htop
  package:
    name: htop
    state: present
    update_cache: yes
