---
- name: Install epel-release CentOS
  yum:
    name: epel-release
    state: present
    update_cache: yes
  when: ansible_distribution == "CentOS"

- name: Install htop
  package:
    name: htop
    state: present
    update_cache: yes
